import type { Metadata } from "next";
import "./globals.css";
import { ChildrenProps } from "@/types";
import NextProvider from "@/NextUiProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <NextProvider>{children}</NextProvider>
      </body>
    </html>
  );
}
