import type { Metadata } from "next";
import "./globals.css";
import { ParamsProps } from "@/types";
import NextProvider from "@/NextUiProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: ParamsProps) {
  const direction = locale === "ar" ? "rtl" : "ltr";
  return (
    <html lang={locale} dir={direction} className="scroll-smooth">
      <body>
        <NextProvider>{children}</NextProvider>
      </body>
    </html>
  );
}
